### ISSUE TITLE
Make the countdown timer visible in the menubar on Mac OS X

### ISSUE THREAD

**Issue by andrewminer** [tomighty/tomighty-osx#1]
I find it very helpful to see the timer counting down until the end of a pomodoro as I'm working.  To that end, it would be great to have the option to make the menu bar item display the time remaining instead of (or in addition to) the app icon when a pomodoro is in progress.

**Comment by eduardonunesp** [comment]
Fine, i have been working in the fork and made some modifications, not sure if it's perfect (i don't know much about OSX development), if you want give a try https://github.com/eduardonunesp/tomighty-osx

**Comment by dvntucker** [comment]
Resolved with https://github.com/tomighty/tomighty-osx/pull/9 and going into release 1.1
