### ISSUE TITLE
Dark Mode compatibility in Yosemite

### ISSUE THREAD

**Issue by javy-** [tomighty/tomighty-osx#14]
Menubar icon does not show up when dark mode is enabled.

**Comment by eduardonunesp** [comment]
:+1: Yeah, i like that too :D

**Comment by totomobile43** [comment]
You can built it yourself, it works!

**Comment by lazzarello** [comment]
Random question, the master branch builds fine but I can't figure out how to actually "install the application" in the sense that I don't know where the build artifact is that I have to launch to get it to show up in the toolbar.

**Comment by lazzarello** [comment]
nm, figured it out:

Product -> Archive -> Export -> "Export as an OS X application"

All good. Thanks for a rad app.

**Comment by eduardonunesp** [comment]
Fine, i have been working in the fork and made some modifications, not sure if it's perfect (i don't know much about OSX development), if you want give a try https://github.com/eduardonunesp/tomighty-osx

**Comment by dvntucker** [comment]
Hi all, closing this issue as a duplicate of https://github.com/tomighty/tomighty-osx/issues/14

This will be fixed in the latest release. Cheers.
